# Site
name: "Tân Nguyễn"
title: "Tân Nguyễn"
description: "Wellcome to my blog"
meta_description: "Wellcome to my blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'https-tannguyenit-github-io'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title

# Authors
authors:
  tannguyen:
    name: tannguyen
    display_name: Tân Nguyễn
    gravatar: 817789f985a387521d6ec4d5a18137c1
    email: tannguyenit95@gmail.com
    web: tannguyenit.github.io
    twitter: https://twitter.com/tannguyenit1995
    description: "I'am developer"
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination
paginate: 12
paginate_path: /page:num
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
google_analytics: UA-116922149-2